// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFkWnkwPr5jAzi1PCkV-AMxnAfSxcpHk',
    appId: '1:212393181149:web:9ba6d3cf81895a6176c034',
    messagingSenderId: '212393181149',
    projectId: 'oua122-bootcamp',
    authDomain: 'oua122-bootcamp.firebaseapp.com',
    storageBucket: 'oua122-bootcamp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KHx15k5u-XZTFVEgKMwNCXreNurYSLk',
    appId: '1:212393181149:android:5bbf697e7c9f6d1a76c034',
    messagingSenderId: '212393181149',
    projectId: 'oua122-bootcamp',
    storageBucket: 'oua122-bootcamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyF5WCSbdjlxWyrSMcuNtBf5P18Vb8GCo',
    appId: '1:212393181149:ios:36d20579369b900076c034',
    messagingSenderId: '212393181149',
    projectId: 'oua122-bootcamp',
    storageBucket: 'oua122-bootcamp.appspot.com',
    iosClientId: '212393181149-0hpgbs92cd91mvuhh1tve7taavdnvsm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyF5WCSbdjlxWyrSMcuNtBf5P18Vb8GCo',
    appId: '1:212393181149:ios:eb69e8c48cfd6e7576c034',
    messagingSenderId: '212393181149',
    projectId: 'oua122-bootcamp',
    storageBucket: 'oua122-bootcamp.appspot.com',
    iosClientId: '212393181149-pmqplooi9cbakdihsjib7sjjt4qbd9k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
